#[derive(Debug, Clone)]
pub enum Instruction {
    Add { dest: u8, src1: u8, src2: u8 },
    Subtract { dest: u8, src1: u8, src2: u8 },
    Multiply { dest: u8, src1: u8, src2: u8 },
    Divide { dest: u8, src1: u8, src2: u8 },
    Modulo { dest: u8, src1: u8, src2: u8 },
    Equal { dest: u8, src1: u8, src2: u8 },
    NotEqual { dest: u8, src1: u8, src2: u8 },
    Greater { dest: u8, src1: u8, src2: u8 },
    GreaterEqual { dest: u8, src1: u8, src2: u8 },
    Less { dest: u8, src1: u8, src2: u8 },
    LessEqual { dest: u8, src1: u8, src2: u8 },
    And { dest: u8, src1: u8, src2: u8 },
    Or { dest: u8, src1: u8, src2: u8 },
    Negate { dest: u8, src: u8 },
    Not { dest: u8, src: u8 },
    LoadConst { dest: u8, src: u16 },
    Move { dest: u8, src: u8 },
    Call,
    Return { src: u8 },
    Jump(u32),
    JumpFalse(u32),
    Print,
}
